name = "my-medusa-store"
compatibility_date = "2024-11-27"
assets = { directory = ".medusa/server" }

[build]
command = "npm run build"
cwd = "build_cwd"
watch_dir = "build_watch_dir"
pages_build_output_dir = ".medusa/server/public/admin"

