name: Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: build api        
        run: yarn workspace api build
      
      - name: build app
        run: yarn workspace app build

      - name: Publish        
        uses: cloudflare/wrangler-action@v3.12.1                        
        with:          
          workingDirectory: api
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}        
